### ISSUE TITLE
Add documentation for OpenSourced extensions

### ISSUE THREAD

**Issue by mburumaxwell** [tinglesoftware/dotnet-extensions#227]
Write docs for:

- [ ] `NumberAbbreviationExtenions` added in #222
- [ ] `StringProtectionExtensions` added in #223
- [ ] `StringSplitExtensions` added in #226
- [ ] `EnumExtensions` added in #228
- [ ] JSON converters added in #228
